In [4]:
import numpy as np

In [3]:
zero_vector = np.zeros(5)  # array with 0 as all elements

In [4]:
zero_matrix = np.zeros((5,3))  # 2d array

In [5]:
zero_vector

array([0., 0., 0., 0., 0.])

In [6]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
empty_matrix = np.empty((2,3))

In [8]:
type(empty_matrix)

numpy.ndarray

In [9]:
type(zero_matrix)

numpy.ndarray

In [10]:
x = np.array([1,2,3])

In [11]:
y= np.array([2,4,6])

In [12]:
X = np.array([[1,3],[5,9]])

In [13]:
X

array([[1, 3],
       [5, 9]])

In [14]:
X.transpose()

array([[1, 5],
       [3, 9]])

In [15]:
X

array([[1, 3],
       [5, 9]])

In [16]:
Y = X.transpose()

In [17]:
Y

array([[1, 5],
       [3, 9]])

In [18]:
x = np.array([1,2,3])
y = np.array([2,4,6])
X = np.array([[1,2,3],[4,6,7]])
Y = np.array([[2,4,6],[8,10,12]])

In [19]:
# access 1D array element
x[2]

3

In [20]:
# slicing
x[0:2]

array([1, 2])

In [22]:
# add 2 arrays up when arrays have same size
z = x + y
z

array([3, 6, 9])

In [23]:
# access 2D array element
X[:,1] # 1st column of table X

array([2, 6])

In [24]:
X[:,0] # 0 column of table X

array([1, 4])

In [26]:
Y[:,1] # 1st column of table Y

array([ 4, 10])

In [25]:
# add X's 1st column and Y's 1st column 
Z = X[:,1] + Y[:,1]
Z

array([ 6, 16])

In [27]:
# 1st row of table X
X[1,:]   # the same as X[1]

array([4, 6, 7])

In [28]:
# add 1st row of table X and 1st row of table Y
X[1,:] + Y[1,:]

array([12, 16, 19])

In [29]:
# if + two list together, it will concatenates them
[2,4] + [6,8]

[2, 4, 6, 8]

In [30]:
# turn the list to np array then use + to do addition
np.array([2,4]) + np.array([6,8])

array([ 8, 12])

In [31]:
# array addition while not same size
a = np.array([1,2])
b = np.array([3,4,5])
a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [5]:
a = np.array([1,2])
b = np.array([2,3,4])
c = b[1:]
b[a] is c

False

In [6]:
b[a]

array([3, 4])

In [7]:
c

array([3, 4])

In [8]:
b[a] == c

array([ True,  True])

In [9]:
id(b[a])

2946933448

In [10]:
id(c)

2956384120

In [11]:
z1 = np.array([1,3,5,7,9])
z2 = z1 + 1  # add 1 to each element

In [12]:
z1

array([1, 3, 5, 7, 9])

In [13]:
z2

array([ 2,  4,  6,  8, 10])

In [14]:
# Python array
index = [0,2,3]  
z1[index]

array([1, 5, 7])

In [15]:
# NumPy array
index = np.array([0,2,3])  
z1[index]  

# index NumPy arrays using either lists or other NumPy arrays

array([1, 5, 7])

In [16]:
# NumPy arrays can also be indexed using logical array
z1

array([1, 3, 5, 7, 9])

In [17]:
z1 > 6

array([False, False, False,  True,  True])

In [18]:
# [logical index vector]
z1[z1 > 6]

array([7, 9])

In [19]:
z2

array([ 2,  4,  6,  8, 10])

In [20]:
z2[z1 > 6]

array([ 8, 10])

In [22]:
# Define logical vector in different way
# Construct a logical vector
index = z1 > 6
index

array([False, False, False,  True,  True])

In [23]:
z1[index]

array([7, 9])

In [24]:
z2[index]

array([ 8, 10])

In [25]:
# Slicing array using ":" returns a view
z1 = np.array([1,3,5,7,9])
w = z1[0:3]   # return a view
w[0] = 3
w

array([3, 3, 5])

In [26]:
z1  # caused by view which update origianl data synchronously 

array([3, 3, 5, 7, 9])

In [27]:
# While indexing array returns a copy of the origianl data
z1 = np.array([1,3,5,7,9])
index = np.array([0,1,2])
w = z1[index]  # return a copy of z1, 2 lists now
w[0] = 3
w

array([3, 3, 5])

In [28]:
z1  # original data not modified

array([1, 3, 5, 7, 9])

In [29]:
# Construct array of 10 linearly spaced array from 0 to 100
# np.linspace(1p,2p,3p) 
# 1p is start point, 2p is end, 3p is #of steps
np.linspace(0, 100, 10) 

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [30]:
# Construct average of 10 logarithmically spaced elements 10-100
# np.logspace()
# 1p is the log(10)=1, 2p is the log(100)=2, 3p is # of elements
np.logspace(1, 2, 10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [31]:
np.logspace(np.log10(250), np.log10(500), 10)

array([250.        , 270.01493472, 291.63225989, 314.98026247,
       340.19750004, 367.43362307, 396.85026299, 428.62199143,
       462.93735614, 500.        ])

In [32]:
# Get the shape of an array/the # of elements in array
X = np.array([[1,2,3],[4,5,6]])
X.shape

(2, 3)

In [33]:
# Get the # of elements of an array with size
X.size

6

In [35]:
# Examine if all elements fulfill some condition

# Generate 10 random numbers from 0-1
x = np.random.random(10)
x

array([0.64997173, 0.36958   , 0.53503248, 0.35922796, 0.49267216,
       0.19849281, 0.63132394, 0.29756721, 0.83177264, 0.85235596])

In [36]:
# Check if any of elements are > 0.9 using np.any()
np.any( x > 0.9)

False

In [37]:
# Check if all elements are >= 0.1 using np.all()
np.all(x >= 0.1)

True